import { motion, AnimatePresence } from "framer-motion";
import { useState, useEffect } from "react";
import styles from "./DemoModal.module.css";
import Backdrop from "./common/Backdrop";

interface DemoModalProps {
  isDemo: boolean;
}

export default function DemoModal({ isDemo }: DemoModalProps) {
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    if (isDemo) {
      setIsOpen(true);
    }
  }, [isDemo]);

  const handleClose = () => {
    setIsOpen(false);
  };

  if (!isDemo) {
    return null;
  }

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            className={styles.modal}
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.8 }}
            transition={{ duration: 0.25 }}
          >
            <div className={styles.modalHeader}>
              <h3 className={styles.modalTitle}>Demo Organization</h3>
              <button
                className={styles.closeButton}
                onClick={handleClose}
                aria-label="Close demo notice"
              >
                ×
              </button>
            </div>
            <div className={styles.modalContent}>
              <p>
                Welcome to a demo organization! All content you see here is
                generated by AI for demonstration purposes and is not real.
              </p>
              <p>
                This includes all posts, messages, and other content within
                this organization.
              </p>
            </div>
            <div className={styles.modalFooter}>
              <button className={styles.primaryButton} onClick={handleClose}>
                Got it!
              </button>
            </div>
          </motion.div>
          <Backdrop onClick={handleClose} />
        </>
      )}
    </AnimatePresence>
  );
}